name: CI

on:
  pull_request:
  schedule:
    - cron:  0 20 * * 6

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Disable adding CR by Windows git
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v1

    - name: Install supplementals (Ubuntu)
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo add-apt-repository ppa:kelleyk/emacs
        sudo apt update
        sudo apt install --no-install-recommends emacs26

    - name: Install scoop (Windows)
      uses: MinoruSekine/setup-scoop@main
      if: contains(matrix.os, 'windows')
      with:
        install_scoop: 'true'
        add_extras_bucket: 'true'
        scoop_update: 'true'
        scoop_checkup: 'false'
        update_path: 'true'
        
    - name: Install supplementals (Windows)
      if: contains(matrix.os, 'windows')
      shell: bash
      run: scoop install emacs shellcheck

    - name: Install supplementals (macOS)
      if: contains(matrix.os, 'macOS')
      run: |
        brew update
        brew install shellcheck
        rm -f /usr/local/bin/2to3
        brew install emacs

    - name: Test run
      shell: bash
      run: |
        make -k -j testrun

    - name: Install elisp-lint
      if: contains(matrix.os, 'ubuntu-latest')
      shell: bash
      run: |
        emacs -Q --batch -l ./.github/workflows/install-elisp-lint.el -f install-elisp-lint-batch

    - name: Lint
      if: contains(matrix.os, 'ubuntu-latest')
      shell: bash
      run: |
        make -k -j lint
