name: CI

env:
  apps_for_windows: "emacs shellcheck"
  cache-version: v1
  hash_seed_file_path: "./.github/workflows/cache_seed_file_for_scoop.txt"

on:
  pull_request:
  schedule:
    - cron:  0 20 * * 6
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Disable adding CR by Windows git
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v1

    - name: Install supplementals (Ubuntu)
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo add-apt-repository ppa:kelleyk/emacs
        sudo apt update
        sudo apt install --no-install-recommends emacs26

    - name: Create cache seed file (Windows)
      if: contains(matrix.os, 'windows')
      run: echo ${{ env.apps_for_windows }} >> ${{ env.hash_seed_file_path }}

    - name: Cache apps installed by scoop (Windows)
      id: cache-installed-apps
      if: contains(matrix.os, 'windows')
      uses: actions/cache@v2
      with:
        path: ~/scoop
        key: cache_version_${{ env.cache-version }}-${{ runner.os }}-${{ hashFiles(env.hash_seed_file_path) }}

    - name: Setup scoop (Windows)
      uses: MinoruSekine/setup-scoop@main
      if: steps.cache-installed-apps.outputs.cache-hit != 'true' && contains(matrix.os, 'windows')
      with:
        install_scoop: true
        add_extras_bucket: true
        scoop_update: true
        scoop_checkup: true
        update_path: true

    - name: Install supplementals (Windows)
      if: steps.cache-installed-apps.outputs.cache-hit != 'true' && contains(matrix.os, 'windows')
      run: |
        scoop install ${{ env.apps_for_windows }}
        scoop cleanup
        scoop cache rm "*"

    - name: Set PATH for scoop if using cache (Windows)
      uses: MinoruSekine/setup-scoop@main
      if: steps.cache-installed-apps.outputs.cache-hit == 'true' && contains(matrix.os, 'windows')
      with:
        install_scoop: false
        add_extras_bucket: false
        scoop_update: false
        scoop_checkup: false
        update_path: true

    - name: Install supplementals (macOS)
      if: contains(matrix.os, 'macOS')
      run: |
        brew update
        brew install shellcheck
        rm -f /usr/local/bin/2to3
        brew install emacs

    - name: Test run
      shell: bash
      run: |
        make -k -j testrun

    - name: Install elisp-lint
      if: contains(matrix.os, 'ubuntu-latest')
      shell: bash
      run: |
        emacs -Q --batch -l ./.github/workflows/install-elisp-lint.el -f install-elisp-lint-batch

    - name: Lint
      if: contains(matrix.os, 'ubuntu-latest')
      shell: bash
      run: |
        make -k -j lint
