name: CI

on:
  pull_request:
  schedule:
    - cron:  0 20 * * 6
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Disable adding CR by Windows git
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v1

    - name: Install supplementals (Ubuntu)
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo add-apt-repository ppa:kelleyk/emacs
        sudo apt update
        sudo apt install --no-install-recommends emacs26

    - name: Cache apps installed by scoop (Windows)
      id: cache-installed-apps
      if: contains(matrix.os, 'windows')
      uses: actions/cache@v2
      with:
        path: ~/scoop
        key: ${{ runner.os }}-${{ hashFiles('./.github/workflows/scoop_apps_to_install.txt') }}

    - name: Setup scoop (Windows)
      uses: MinoruSekine/setup-scoop@v1
      if: steps.cache-installed-apps.outputs.cache-hit != 'true' && contains(matrix.os, 'windows')
        
    - name: Install supplementals (Windows)
      if: steps.cache-installed-apps.outputs.cache-hit != 'true' && contains(matrix.os, 'windows')
      shell: pwsh
      run: |
        scoop update
        scoop bucket add extras
        ./.github/workflows/scoop_install_apps.ps1 ./.github/workflows/scoop_apps_to_install.txt

    - name: Install supplementals (macOS)
      if: contains(matrix.os, 'macOS')
      run: |
        brew update
        brew install shellcheck
        rm -f /usr/local/bin/2to3
        brew install emacs

    - name: Test run
      shell: bash
      run: |
        make -k -j testrun

    - name: Install elisp-lint
      if: contains(matrix.os, 'ubuntu-latest')
      shell: bash
      run: |
        emacs -Q --batch -l ./.github/workflows/install-elisp-lint.el -f install-elisp-lint-batch

    - name: Lint
      if: contains(matrix.os, 'ubuntu-latest')
      shell: bash
      run: |
        make -k -j lint
