name: CI

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Install Emacs (Ubuntu)
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo add-apt-repository ppa:kelleyk/emacs
        sudo apt update
        sudo apt install emacs26

    - name: Install Emacs (Windows)
      if: contains(matrix.os, 'windows')
      run: |
        Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
        iex (New-Object net.webclient).downloadstring('https://get.scoop.sh')
        scoop bucket add extras
        scoop install emacs
      shell: pwsh

    - name: Install Emacs (macOS)
      if: contains(matrix.os, 'macOS')
      run: |
        brew cask install emacs

    - name: Install elisp-lint
      run: |
        export PATH=$PATH:$HOME/scoop/shims
        emacs -Q --batch -l ./.github/workflows/install-elisp-lint.el -f install-elisp-lint-batch
      shell: bash

    - name: Lint
      run: |
        export PATH=$PATH:$HOME/scoop/shims
        make -k -j lint
      shell: bash
