name: CI

on:
  pull_request:
  schedule:
    - cron:  0 20 * * 6

env:
  os_for_lint: ubuntu-latest
  apps_to_install: shellcheck

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            package_update_command: sudo add-apt-repository ppa:kelleyk/emacs; sudo apt update
            package_install_command: sudo apt install --no-install-recommends
            emacs_package_name: emacs26
          - os: ubuntu-16.04
            package_update_command: sudo add-apt-repository ppa:kelleyk/emacs; sudo apt update
            package_install_command: sudo apt install --no-install-recommends
            emacs_package_name: emacs26
          - os: windows-latest
            package_update_command: ':'
            package_install_command: scoop install
            emacs_package_name: emacs
          - os: macOS-latest
            package_update_command: brew update --preinstall; rm -f /usr/local/bin/2to3
            package_install_command: brew install
            emacs_package_name: emacs

    runs-on: ${{ matrix.os }}

    steps:
    - name: Disable adding CR by Windows git
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v1

    - name: Install scoop (Windows)
      uses: MinoruSekine/setup-scoop@main
      if: contains(matrix.os, 'windows')
      with:
        install_scoop: 'true'
        add_extras_bucket: 'true'
        scoop_update: 'true'
        scoop_checkup: 'false'
        update_path: 'true'

    - name: Install supplementals
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
      shell: bash
      run: |
        ${{ matrix.package_update_command }}
        ${{ matrix.package_install_command }} ${{ env.apps_to_install }} ${{ matrix.emacs_package_name }}

    - name: Test run
      shell: bash
      run: |
        make -k -j testrun

    - name: Install elisp-lint
      if: contains(matrix.os, env.os_for_lint)
      shell: bash
      run: emacs -Q --batch -l ./.github/workflows/install-elisp-lint.el -f install-elisp-lint-batch

    - name: Lint
      if: contains(matrix.os, env.os_for_lint)
      shell: bash
      run: make -k -j lint
