name: Emacs

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: 0 20 * * 6
  workflow_dispatch:

jobs:
  TestRun:
    name: Test run

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest, macos-13]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Emacs
        uses: ./.github/actions/install_emacs

      - name: Check version of Emacs
        shell: bash
        run: emacs --version

      - name: Check load-path
        shell: bash
        run: ./.github/workflows/show_emacs_loadpath.sh

      - name: Check system-name
        shell: bash
        run: ./.github/workflows/show_emacs_system_name.sh

      - name: Test run
        shell: bash
        run: |
          make -k -j testrun

  ElispLint:
    name: elisp-lint

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Emacs
        uses: ./.github/actions/install_emacs

      - name: Install elisp-lint
        shell: bash
        run: emacs -Q --batch -l ./.github/workflows/install-elisp-lint.el -f install-elisp-lint-batch

      - name: elisp-lint
        shell: bash
        run: make -k -j elisp-lint-all

  UnitTests:
    name: Unit tests

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest, macos-13]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Emacs
        uses: ./.github/actions/install_emacs

      - name: Unit tests for Emacs Lisp
        shell: bash
        run: make -k -j test
